### ISSUE TITLE
Remarks

### ISSUE THREAD

**Issue by lishine** [gactjs/store#2]
Hi,

I appreciate your investment in this lib.
But I will mention a few things.

State hoisting, you mentioned it many times, but from a brief reading I didn't understand it.

A few libs that construct state as a tree.
https://github.com/ForsakenHarmony/parket
https://github.com/mobxjs/mobx-state-tree
https://github.com/ctrlplusb/easy-peasy

Personally I will use react-context. It can be lifted wherever. And used with subscriptions. Such as here
https://github.com/dai-shi/use-context-selector

**Comment by contrarian** [comment]
Surely, constructing state as a tree is not a new idea. The most popular state container Redux uses this approach. 

However, organizing your state into a single tree only works when it's coupled with **event sourcing** and **exact change tracking**. These mechanisms augment a state tree into an **accountable centralized state tree**. 

Using React's context with subscriptions may help with performance, but it does nothing to solve the tractability issues with context. 

I recommend giving the [white paper](https://github.com/gactjs/store/blob/master/docs/white-paper.md) a careful read.

**Comment by lishine** [comment]
Thanks
